name: Actions
on:
  pull_request: 
    branches: ["master", "develop"]
  workflow_dispatch:
jobs:
  test:
    name: Build with tests
    runs-on: macos-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v3
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with:
          xcode-version: latest-stable
      - name: Show current Xcode version
        run: xcodebuild -version
      - name: Build and test
        run: xcodebuild clean build test -project octosub.xcodeproj -scheme octosub -resultBundlePath coverage/result.xcresult -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' -enableCodeCoverage YES | xcpretty
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" coverage/result.xcresult > coverage_report.lcov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2