# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "main", "develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        macos:
          - 12
        xcode:
          - latest-stable
    runs-on: macos-${{ matrix.macos }}
    steps:
      - name: Get Sources
        uses: actions/checkout@v2
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with:
          xcode-version: "14.0"

      - name: Xcode Build
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: octosub.xcodeproj
          scheme: octosub
          action: build
          
      - name: Xcode Test
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: octosub.xcodeproj
          scheme: octosub
          action: test
